{% set version = '1.1-21' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mcpan
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MCPAN_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MCPAN/MCPAN_{{ version }}.tar.gz
  sha256: a1a8e04ce53447d82e5e3889b90a0e22fb06ac80e2b3cee54fb808845e073560

build:
  number: 1006
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mcmcpack
    - r-magic
    - r-multcomp
    - r-mvtnorm
    - r-plyr
  run:
    - r-base
    - r-mcmcpack
    - r-magic
    - r-multcomp
    - r-mvtnorm
    - r-plyr

test:
  commands:
    - $R -e "library('MCPAN')"           # [not win]
    - "\"%R%\" -e \"library('MCPAN')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MCPAN
  license: GPL-2.0-only
  summary: Multiple contrast tests and simultaneous confidence intervals based on normal approximation.
    With implementations for binomial proportions in a 2xk setting (risk difference
    and odds ratio), poly-3-adjusted tumour rates, biodiversity indices (multinomial
    data)  and expected values under lognormal assumption. Approximative power  calculation
    for multiple contrast tests of binomial and Gaussian data.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
