appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: sECnwTFE5q0pLhRdKsnFFQLkWYiejTwZdPDtB7o6Nv1uqeGU12jIhIFaROIQwEzZkCZ3qwIhq0KPEfkp0QMU0+tcBLLJPgUNMozxPrRz6yTiDW6dbLIVP/NfqaIaBjgCNxmQrDWAoH7j/j/bTU8lQMsthAk+V3mFIOtZT4m3/CcRCxlhrfMCYospRhmRcugcmiHi4GLw9xh23+z4vgpHJLakVafntkWnFdLpaIM1ErEE7l7VZNsR+wQTx4/yl54dw0O2LO8xaXOStUz3S1+kPyp/Y50esK43uasG/3eo1Xm+WH2fmJruBMqw8hr3BSFejNAMDr1i5iud1k5SMFAsfBBJTpBsaEJlNG6GkMrXUW+98NIWPgsPlL2++tWPs2/qUPg+45WbpDLKO0KkvlNJEbQsAwiLxrJKy/roStXiJDuikajcHkUFhyIXbwexnuusZYohtw7zNxY2Cdyv7MA7OelribXV3v91Ih1mUtnax56C6UFn2VSj5L0YHwttpuShOT94FMrr/8J0swmWHdV1Povi6hpcE8vSbux7aoIPF2z+pJuxqQtDQpiIH2uf4ACMZXYWDsLqV2bw++B7INt+BDCmb++femV05VIws08AqQ3pO4+58VPAx4REoxttmuexmugTw1vW26GVtSWGIV+VhnaRIB4lGHgbr0fwBuui5ek=
