travis:
  secure:
    BINSTAR_TOKEN: rlTuSLHbzp7rm8RdwtftspYa6RcAcQdlXq8ocdy5vSkdjI463HDOGfOaUfSkpI/Z6PhgL68M1pILTiiFFx6U2MgoDDKutDDdpTaZl+tigK1tahzBRfKmT8DW1N6oJBzYtYZ+wm6OHHWiPs+9c4lANuWBJDXnyEprT8UaMQYzguaCaFf/IMYrNvknoRGqSoauS3ImWPLAMgPke6TUd/BcHbuVF5KlD8vzVlsVnnMcfp2nb6cd8WzjJZWYgNdLCL6oAEkAh6w9eTSMYxnz04GgvFrnMd0BnsYFOZQiid0HaqhxJBwIyP0GmZvGtML6ZTMNJA7xwWS4GlfqlqEcUuMVDehOYhH91O3JCtZ7j44hD2QXWsO5Bu0HLnHcpEAhjJF7LQB99AHV0gbycxiBy4as8Pi8Mg6JCsJ7oUItqt6StJE+9Anj3Q/TlikjRPOsk29T/oTphlWNJIyVbSnP8M76tATnM7MYc1kMFijgm31SCw3kR+1/VkxBkb12F6hMyeYwTWk5fJhOEGcmn2cwG/44bSe8pCHjjFzDOamRR1Oh1WPYP3p9YoezHE9rl0HR+iXPAjkDfXP6AGcwLRkjzllppdnmuTasnlU7Fs/c7Qhw9ZBGt/yBkjeCx7WbfUFtTQH8SKID4waGbvDpLCRXo9kbgwigPMoYTuJkdGeXzs42b+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
